# Generated by Django 3.2.19 on 2023-10-06 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=256, verbose_name='Полное наименование')),
                ('shortName', models.CharField(max_length=256, verbose_name='Сокращенное наименование')),
                ('address', models.CharField(max_length=256, verbose_name='Адрес')),
                ('ogrn', models.IntegerField(blank=True, verbose_name='ОГРН/ОГРНИП')),
                ('licenseNumber', models.IntegerField(blank=True, verbose_name='Номер лицензии')),
                ('licenseDate', models.DateTimeField(verbose_name='Дата регистрации лицензии')),
                ('licenseStatus', models.BooleanField(default=False, verbose_name='Статус лицензии')),
                ('pccDate', models.DateTimeField(blank=True, verbose_name='Крайний срок первичного прохождения лицензиатами процедуры периодического подтверждения соответствия лицензионным требованиям')),
                ('inn', models.IntegerField(blank=True, verbose_name='ИНН')),
                ('work1', models.BooleanField(default=False, verbose_name='ОЛД_Разработка проектной документации по консервации, ремонту, реставрации, приспособлению и воссозданию объектов культурного наследия (памятников истории и культуры) народов Российской Федерации')),
                ('work2', models.BooleanField(default=False, verbose_name='ОЛД_Разработка проектной документации по инженерному укреплению объектов культурного наследия (памятников истории и культуры) народов Российской Федерации')),
                ('work3', models.BooleanField(default=False, verbose_name='ОЛД_Реставрация и воссоздание наружных и внутренних декоративно-художественных покрасок')),
                ('work4', models.BooleanField(default=False, verbose_name='ОЛД_Реставрация, консервация и воссоздание штукатурной отделки')),
                ('work5', models.BooleanField(default=False, verbose_name='ОЛД_Реставрация, консервация и воссоздание архитектурно-лепного декора')),
                ('work6', models.BooleanField(default=False, verbose_name='ОЛД_Реставрация, консервация и воссоздание поверхности из искусственного мрамора')),
                ('work7', models.BooleanField(default=False, verbose_name='ОЛД_Ремонт, реставрация и воссоздание кровель')),
                ('work8', models.BooleanField(default=False, verbose_name='ОЛД_Ремонт, реставрация и воссоздание металлических конструкций')),
                ('work9', models.BooleanField(default=False, verbose_name='ОЛД_Ремонт, реставрация и воссоздание оконных и дверных приборов')),
                ('work10', models.BooleanField(default=False, verbose_name='ОЛД_Ремонт, реставрация, консервация и воссоздание деревянных конструкций и деталей')),
                ('work11', models.BooleanField(default=False, verbose_name='ОЛД_Реставрация и воссоздание резьбы по деревянным конструкциям')),
                ('work12', models.BooleanField(default=False, verbose_name='ОЛД_Реставрация и воссоздание паркетных полов')),
                ('work13', models.BooleanField(default=False, verbose_name='ОЛД_Ремонт, реставрация и консервация ограждающих конструкций и распорных систем')),
                ('work14', models.BooleanField(default=False, verbose_name='ОЛД_Ремонт, реставрация, консервация и воссоздание оснований и фундаментов')),
                ('work15', models.BooleanField(default=False, verbose_name='ОЛД_Ремонт, реставрация, консервация и воссоздание кладок, конструкций')),
                ('work16', models.BooleanField(default=False, verbose_name='ОЛД_Реставрация, консервация и воссоздание мебели')),
                ('work17', models.BooleanField(default=False, verbose_name='ОЛД_Реставрация, консервация и воссоздание резьбы по дереву')),
                ('work18', models.BooleanField(default=False, verbose_name='ОЛД_Реставрация, воссоздание и консервация тканей, гобеленов и ковров')),
                ('work19', models.BooleanField(default=False, verbose_name='ОЛД_Реставрация и воссоздание осветительных приборов')),
                ('work20', models.BooleanField(default=False, verbose_name='ОЛД_Реставрация и воссоздание деталей из черного и цветных металлов')),
                ('work21', models.BooleanField(default=False, verbose_name='ОЛД_Реставрация и воссоздание позолоты')),
                ('work22', models.BooleanField(default=False, verbose_name='ОЛД_Реставрация и воссоздание керамического декора')),
                ('work23', models.BooleanField(default=False, verbose_name='ОЛД_Реставрация и воссоздание мозаики')),
                ('work24', models.BooleanField(default=False, verbose_name='ОЛД_Реставрация и воссоздание янтарного набора')),
                ('work25', models.BooleanField(default=False, verbose_name='ОЛД_Реставрация и воссоздание графики')),
                ('work26', models.BooleanField(default=False, verbose_name='ОЛД_Реставрация, консервация и воссоздание монументальной живописи')),
                ('work27', models.BooleanField(default=False, verbose_name='ОЛД_Реставрация, консервация и воссоздание станковой живописи')),
                ('work28', models.BooleanField(default=False, verbose_name='ОЛД_Реставрация, консервация и воссоздание скульптуры')),
                ('work29', models.BooleanField(default=False, verbose_name='ОЛД_Реставрация и воссоздание исторического ландшафта и произведений садово-паркового искусства')),
                ('work30', models.BooleanField(default=False, verbose_name='ОЛД_Приспособление инженерных систем и оборудования')),
                ('work31', models.BooleanField(default=False, verbose_name='ОЛД_Приспособление систем электрообеспечения')),
                ('newWork1', models.BooleanField(default=False, verbose_name='Разработка проектной документации по консервации, реставрации и воссозданию объектов культурного наследия (памятников истории и культуры) народов Российской Федерации')),
                ('newWork2', models.BooleanField(default=False, verbose_name='Разработка проектной документации по ремонту и приспособлению объектов культурного наследия (памятников истории и культуры) народов Российской Федерации')),
                ('newWork3', models.BooleanField(default=False, verbose_name='Реставрация, консервация и воссоздание оснований, фундаментов, кладок, ограждающих конструкций и распорных систем')),
                ('newWork4', models.BooleanField(default=False, verbose_name='Реставрация, консервация и воссоздание металлических конструкций и деталей')),
                ('newWork5', models.BooleanField(default=False, verbose_name='Реставрация, консервация и воссоздание деревянных конструкций и деталей')),
                ('newWork6', models.BooleanField(default=False, verbose_name='Реставрация, консервация и воссоздание декоративно-художественных покрасок, штукатурной отделки и архитектурно-лепного декора')),
                ('newWork7', models.BooleanField(default=False, verbose_name='Реставрация, консервация и воссоздание конструкций и деталей из естественного и искусственного камней')),
                ('newWork8', models.BooleanField(default=False, verbose_name='Реставрация, консервация и воссоздание произведений скульптуры и декоративно-прикладного искусства')),
                ('newWork9', models.BooleanField(default=False, verbose_name='Реставрация, консервация и воссоздание живописи (монументальной, станковой)')),
                ('newWork10', models.BooleanField(default=False, verbose_name='Реставрация, консервация и воссоздание исторического ландшафта и произведений садово-паркового искусства')),
                ('newWork11', models.BooleanField(default=False, verbose_name='Ремонт и приспособление объектов культурного наследия (памятников истории и культуры) народов Российской Федерации')),
                ('orderNumber', models.IntegerField(verbose_name='Номер приказа о предоставлении лицензии')),
                ('orderDate', models.DateTimeField(verbose_name='Дата приказа')),
                ('changeOrder', models.CharField(blank=True, max_length=256, verbose_name='Номер приказа о переоформлении лицензии')),
                ('stoppingInfo', models.CharField(blank=True, max_length=256, verbose_name='Основание')),
                ('terminationStatement', models.IntegerField(blank=True, verbose_name='Основание прекращения действия лицензии')),
                ('terminationDate', models.DateTimeField(blank=True, verbose_name='Дата прекращения действия лицензии')),
                ('inspectionsInfo', models.CharField(blank=True, max_length=512, verbose_name='Основание проведения проверки')),
                ('penaltyInfo', models.DateTimeField(blank=True, verbose_name='Дата постановления')),
                ('pathInfo', models.CharField(max_length=512, verbose_name='Сведения о первоисточнике записи')),
                ('category', models.CharField(max_length=256, verbose_name='Категория объекта в исходной информационной системе')),
                ('createDate', models.DateTimeField(verbose_name='Дата создания записи')),
                ('updateDate', models.DateTimeField(verbose_name='Дата обновления записи')),
            ],
            options={
                'verbose_name': 'Data',
                'verbose_name_plural': 'Data',
                'ordering': ['-id'],
            },
        ),
    ]
