# Generated by Django 3.2.19 on 2023-10-06 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='address',
            field=models.CharField(blank=True, max_length=256, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='data',
            name='licenseNumber',
            field=models.CharField(blank=True, max_length=256, verbose_name='Номер лицензии'),
        ),
        migrations.AlterField(
            model_name='data',
            name='shortName',
            field=models.CharField(blank=True, max_length=256, verbose_name='Сокращенное наименование'),
        ),
    ]
