# Generated by Django 3.2.19 on 2023-10-06 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20231006_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='orderNumber',
            field=models.IntegerField(blank=True, verbose_name='Номер приказа о предоставлении лицензии'),
        ),
    ]
