# Generated by Django 3.2.19 on 2023-10-06 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_data_ordernumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='inn',
            field=models.IntegerField(blank=True, default=0, verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='data',
            name='ogrn',
            field=models.IntegerField(blank=True, default=0, verbose_name='ОГРН/ОГРНИП'),
        ),
        migrations.AlterField(
            model_name='data',
            name='orderNumber',
            field=models.IntegerField(blank=True, default=0, verbose_name='Номер приказа о предоставлении лицензии'),
        ),
        migrations.AlterField(
            model_name='data',
            name='terminationStatement',
            field=models.IntegerField(blank=True, default=0, verbose_name='Основание прекращения действия лицензии'),
        ),
    ]
